### ISSUE TITLE
 Error in nextTick: "SecurityError: Failed to read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules"

### ISSUE THREAD

**Issue by artiely** [Power-kxLee/vue-print-nb#29]
Error in nextTick: "SecurityError: Failed to read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules"

**Comment by matiyin** [comment]
I ran into the same issue, and it's related to the browser loading an external stylesheet, which runs into a CORS security problem in Chrome. Externally loaded stylesheets cannot be accessed by javascript.
See https://stackoverflow.com/questions/49993633/uncaught-domexception-failed-to-read-the-cssrules-property?rq=1

Solution: load your stylesheets locally / from the same domain. In my case it was caused by loading an external Icomoon stylesheet.
