### ISSUE TITLE
如何调用打印结束的回调函数，我现在调打印后原先调页面内容会变空白

### ISSUE THREAD

**Issue by Nebulazheng** [Power-kxLee/vue-print-nb#41]
endCallback()
1:这个api在vue页面中如何调用呢。既我在打印成功后监听成功回调
2:调用打印，页面打印区域调内容就全空白啦

**Comment by Nebulazheng** [comment]
变空白的内容是img图片

**Comment by chenl01** [comment]
怎么得知打印和取消的回调啊，现在打印取消都回调endCallback()了。

**Comment by pbsdjames** [comment]
The endCallback() event does not appear to fire after the printing but rather on loading the view.  I added an alert to my call back function and that appears when the page loads, not after the printing.  Below is a snippet from my code.

`data() {
    return {
        printObj: {
        id: "app",
        popTitle: 'print',
        endCallback: this.printComplete(),
      },
      isPrinting: false, 
    }
},
methods: {
    printComplete(){
      this.isPrinting = false;
      alert('printing is done');
    },
}`
this will cause the alert message to appear when loading the view.  The expected behavior is to see it after the print view is done.  The objective is to show a section only during printing and then hide it once printing is complete.

**Comment by Power-kxLee** [comment]
Updated version Thank  @chenl01 @pbsdjames @zhangdaiscott @Power-kxLee
